- type: latheRecipe
  parent: BaseAmmoRecipe
  id: MagazineMiniMachineGunBox
  result: MagazineMiniMachineGunBox
  materials:
    Steel: 1000
  time: 7

- type: latheRecipePack
  id: SecurityAmmoStaticMini
  recipes:
    - MagazineMiniMachineGunBox