- type: job
  id: SeniorOfficer
  name: job-name-senior-officer
  description: job-description-senior-officer
  playTimeTracker: JobSeniorOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 3600 # 1 hours
    - !type:RoleTimeRequirement
      role: JobDetective
      time: 7200 # 2 hours
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 3600 # 1 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10800 # 3 hours
    - !type:AgeRequirement
      requiredAge: 24
  startingGear: SeniorOfficerGear
  icon: "JobIconSeniorOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - External
  - Cryogenics
  #start-backmen: currency
  minBankBalance: 150
  maxBankBalance: 250
  wageDepartment: Security
  wage: 70
  #end-backmen: currency
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SeniorOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretSeniorOfficer
    ears: ClothingHeadsetSecurity
    pocket1: WeaponRevolverDeckard
  storage:
    back:
    - Flash
    - SpeedLoaderMagnum
    - SpeedLoaderMagnum
    - SpeedLoaderMagnum
    - HyperLinkBookCorporateLaw
    - HyperLinkBookSOPSecurity
    - RubberStampSeniorOfficer # DS14
